### Create a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Sample Blog",
    "author": "John Doe",
    "url": "http://example.com/sample-blog",
    "likes": 10,
	"userId": "65237e35dff53e142476408b"
}