### Create a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Sample Blog",
    "author": "John Doe",
    "url": "http://example.com/sample-blog",
    "likes": 10
}